[package]
name = "spacetime_engine_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "spacetime_engine_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"