//! UI-agnostic semantic metadata used by inspection derives and hosts.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectSectionId(pub &'static str);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectFieldId(pub &'static str);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectActionId(pub &'static str);

/// Stable optional override for value-widget selection.
///
/// The ID lives in UI-agnostic metadata. An egui host, terminal host, or other
/// presentation layer may resolve the same semantic hint differently.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectWidgetId(pub &'static str);

/// How an inspected value may be changed.
///
/// This is intentionally richer than a `read_only: bool`: presentation consumes
/// authority supplied by the domain; it never creates authority merely because
/// `&mut T` happens to be technically obtainable.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InspectAccess {
    #[default]
    ReadOnly,
    /// The inspected value itself is authoritative and may be mutated directly.
    Direct,
    /// Changes must pass through validation/setter logic.
    Validated,
    /// Changes belong to an authoring transaction/undo history.
    Transactional,
    /// Changes are requests/commands to the owning domain rather than field writes.
    Command,
}

impl InspectAccess {
    pub fn editable(self) -> bool {
        self != Self::ReadOnly
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::ReadOnly => "read-only",
            Self::Direct => "direct",
            Self::Validated => "validated",
            Self::Transactional => "transactional",
            Self::Command => "command",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectUnit(pub &'static str);

impl InspectUnit {
    pub const KELVIN: Self = Self("K");
    pub const JOULE: Self = Self("J");
    pub const WATT: Self = Self("W");
    pub const HEAT_CAPACITY: Self = Self("J/K");
    pub const COOLING_COEFFICIENT: Self = Self("W/K");
    pub const METER: Self = Self("m");
    pub const METERS_PER_SECOND: Self = Self("m/s");
    pub const METERS_PER_SECOND_SQUARED: Self = Self("m/s²");
    pub const DENSITY: Self = Self("kg/m³");
    pub const SPECIFIC_HEAT_CAPACITY: Self = Self("J/(kg·K)");
    pub const THERMAL_CONDUCTIVITY: Self = Self("W/(m·K)");
    pub const THERMAL_DIFFUSIVITY: Self = Self("m²/s");
}

#[derive(Debug, Clone, Copy)]
pub struct InspectNumberFormat {
    pub significant_digits: u8,
}

impl Default for InspectNumberFormat {
    fn default() -> Self {
        Self {
            significant_digits: 5,
        }
    }
}

impl InspectNumberFormat {
    pub const fn significant_digits(significant_digits: u8) -> Self {
        Self { significant_digits }
    }
}

/// UI hints for numeric input. These are presentation affordances, not domain
/// validation. Domains must still validate every edit request they accept.
#[derive(Debug, Clone, Copy)]
pub struct InspectNumberInput {
    pub speed: f64,
    pub minimum: Option<f64>,
    pub maximum: Option<f64>,
    pub slider: bool,
}

impl Default for InspectNumberInput {
    fn default() -> Self {
        Self {
            speed: 0.1,
            minimum: None,
            maximum: None,
            slider: false,
        }
    }
}

impl InspectNumberInput {
    pub const fn speed(speed: f64) -> Self {
        Self {
            speed,
            minimum: None,
            maximum: None,
            slider: false,
        }
    }

    pub const fn range(mut self, minimum: f64, maximum: f64) -> Self {
        self.minimum = Some(minimum);
        self.maximum = Some(maximum);
        self
    }

    pub const fn slider(mut self) -> Self {
        self.slider = true;
        self
    }
}

/// Static metadata generated by [`Inspect`] implementations.
///
/// This contains presentation-independent meaning only. In particular, a widget
/// override is a stable ID rather than an egui callback/function pointer.
#[derive(Debug, Clone, Copy)]
pub struct InspectFieldMetadata {
    pub id: InspectFieldId,
    pub rust_name: &'static str,
    pub rust_type_name: &'static str,
    pub label: &'static str,
    pub symbol: Option<&'static str>,
    pub access: InspectAccess,
    pub unit: Option<InspectUnit>,
    pub hint: Option<&'static str>,
    pub role: Option<&'static str>,
    pub widget: Option<InspectWidgetId>,
    pub number_input: Option<InspectNumberInput>,
}

impl InspectFieldMetadata {
    pub const fn new(
        id: InspectFieldId,
        rust_name: &'static str,
        rust_type_name: &'static str,
        label: &'static str,
    ) -> Self {
        Self {
            id,
            rust_name,
            rust_type_name,
            label,
            symbol: None,
            access: InspectAccess::ReadOnly,
            unit: None,
            hint: None,
            role: None,
            widget: None,
            number_input: None,
        }
    }
}

#[derive(Debug)]
pub struct InspectTypeMetadata {
    pub rust_name: &'static str,
    pub label: &'static str,
    pub fields: &'static [InspectFieldMetadata],
}
