[package]
name = "loo-cast"
version = "0.5.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.11.2"
bevy_rapier2d = { version = "0.22.0", features = [ "debug-render-2d" ] }
rand = "0.8.5"
noise = "0.8"
image = "0.24.7"
serde = "1.0.185"
serde_json = "1.0"
futures = "0.3"
num-bigint = "0.4"
num-traits = "0.2"
lazy_static = "1.4"
queues = "1.0.2"