[workspace]
resolver = "3"
members = ["spacetime-engine", "loo-cast-game", "loo-cast-packagepack"]

[workspace.package]
version = "0.5.0"
edition = "2024"

[profile.dev]
opt-level = 1
debug = true
incremental = true
lto = false

# Keep engine code debuggable while fully optimizing dependency hot loops.
# Avian explicitly recommends this for development runtime performance.
[profile.dev.package."*"]
opt-level = 3

[profile.profiling]
inherits = "release"
debug = 1
strip = "none"

[workspace.dependencies]
glam = "0.32.1"
