schema = 1

[workspace]
name = "loo-cast"
organization = "ghf-studios"
version = "0.5.0"
repository = "https://github.com/GHF-Studios/Loo-Cast"

[toolchain]
channel = "stable"
version = "1.97.0"
date = "2026-07-09"

[[project]]
name = "loo-cast"
path = "."
