schema = 1

[workspace]
name = "loo-cast"
organization = "ghf-studios"
version = "0.5.0"
repository = "https://github.com/GHF-Studios/Loo-Cast"

[workspace.runtime]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-gnullvm",
]

[[workspace.projects]]
path = "spacetime-engine"

[[workspace.projects]]
path = "loo-cast-game"

[[workspace.projects]]
path = "loo-cast-packagepack"
