private fn phenomenon_catalog() {
    [
        phn_def_hair_pin(),
        phn_def_diesel_engine(),
        phn_def_spice_grinder(),
        phn_def_f18_fighter_jet(),
        phn_def_car_key(),
        phn_def_drug_prescription(),
        phn_def_trash_bin(),
        phn_def_neutron_star(),
        phn_def_galactic_cluster(),
        phn_def_galaxy(),
        phn_def_nebula(),
        phn_def_cloud(),
        phn_def_apple()
    ]
}
