[camera]
default_zoom = 1.0
min_zoom = 0.03125
max_zoom = 32.0
base_zoom_speed = 1.0
follow_smoothness = 0.15

[chunk]
size = 64.0
default_z = -10.0

[chunk_loader]
default_radius = 8

[player]
movement_speed = 250.0

[workflow]
timeout_frames_per_stage = 30