//! Build-time embedding for repository developer-script defaults.
//!
//! runtime-script-default-overlay-v1
//!
//! The running game never edits repository scripts. Instead, every `.rhai`
//! source under repo `scripts/` is embedded into the built executable. Runtime
//! startup materializes that immutable build payload into a defaults tree and
//! seeds a separate writable live tree.

use std::{
    env, fs,
    path::{Component, Path, PathBuf},
};

const MAX_SCRIPT_FILES: usize = 1_024;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"));
    let source_root = manifest_dir
        .parent()
        .expect("spacetime-engine lives under the workspace root")
        .join("scripts");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set"));
    let generated = out_dir.join("embedded_developer_scripts.rs");

    println!("cargo:rerun-if-changed={}", source_root.display());

    let mut scripts = Vec::<(String, String, PathBuf)>::new();
    if source_root.is_dir() {
        collect_scripts(&source_root, &source_root, &mut scripts);
    }
    scripts.sort_by(|left, right| left.0.cmp(&right.0));

    let mut output = String::from(
        "// @generated by spacetime-engine/build.rs\n\
         pub const EMBEDDED_DEVELOPER_SCRIPTS: &[(&str, &str)] = &[\n",
    );
    for (logical, source, absolute) in scripts {
        println!("cargo:rerun-if-changed={}", absolute.display());
        output.push_str("    (");
        output.push_str(&format!("{logical:?}"));
        output.push_str(", ");
        output.push_str(&format!("{source:?}"));
        output.push_str("),\n");
    }
    output.push_str("];\n");

    fs::write(&generated, output).expect("write embedded developer-script table");
}

fn collect_scripts(root: &Path, directory: &Path, out: &mut Vec<(String, String, PathBuf)>) {
    if out.len() >= MAX_SCRIPT_FILES {
        panic!("developer script source limit exceeded ({MAX_SCRIPT_FILES})");
    }

    let mut entries = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("read {} failed: {error}", directory.display()))
        .collect::<Result<Vec<_>, _>>()
        .unwrap_or_else(|error| panic!("read {} failed: {error}", directory.display()));
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        let path = entry.path();
        let file_type = entry
            .file_type()
            .unwrap_or_else(|error| panic!("stat {} failed: {error}", path.display()));

        if file_type.is_dir() {
            if entry.file_name().to_string_lossy().starts_with('.') {
                continue;
            }
            collect_scripts(root, &path, out);
            continue;
        }

        if !file_type.is_file() || path.extension().and_then(|value| value.to_str()) != Some("rhai")
        {
            continue;
        }

        let relative = path
            .strip_prefix(root)
            .expect("collected script remains under source root");
        let logical = relative
            .components()
            .filter_map(|component| match component {
                Component::Normal(value) => Some(value.to_string_lossy().into_owned()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("/");
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("read {} failed: {error}", path.display()));
        out.push((logical, source, path));
    }
}
