schema = 1

[engine]
name = "spacetime-engine"
version.workspace = true

[[traits]]
name = "render-backend"

[[slots]]
name = "renderer"
trait = "ghf-studios/loo-cast/spacetime-engine/render-backend"
cardinality = "one"
