//! Deterministic volumetric void morphology for rocky celestial bodies.
//!
//! Outer planetary shape remains the canonical radial surface. This module adds
//! true 3D negative-space features beneath/through that surface so dense voxel
//! realizations can contain tunnels, chambers, entrances, arches and overhangs.
//!
//! The returned value is an SDF for the *void volume*: negative is inside a
//! cave. Subtracting that void from solid terrain uses `max(solid_sdf, -void_sdf)`.

use bevy::{math::DVec3, prelude::Vec3};

use super::super::noise::value_noise_3d;

const CAVE_MIN_DEPTH_METRES: f64 = -12.0;
pub(super) const CAVE_MAX_DEPTH_METRES: f64 = 2_400.0;

#[inline]
fn local_f32(point: DVec3) -> Vec3 {
    Vec3::new(point.x as f32, point.y as f32, point.z as f32)
}

#[inline]
fn tunnel_intersection_sdf(
    point: Vec3,
    wavelength_a: f32,
    wavelength_b: f32,
    width_a: f32,
    width_b: f32,
    metres_per_noise_unit: f64,
    seed_a: u32,
    seed_b: u32,
    offset_a: Vec3,
    offset_b: Vec3,
) -> f64 {
    // Intersection of two thick zero-isosurfaces produces tube-like curves
    // rather than the broad sheet caves generated by abs(noise) alone.
    let a = value_noise_3d(point / wavelength_a + offset_a, seed_a).abs();
    let b = value_noise_3d(point / wavelength_b + offset_b, seed_b).abs();
    let normalized = (a - width_a).max(b - width_b);
    f64::from(normalized) * metres_per_noise_unit
}

/// Signed distance-ish field for rocky cave voids in body-local metres.
///
/// This is intentionally a pseudo-SDF rather than exact Euclidean distance.
/// Only the zero crossing and stable sign are required by the current
/// reconstructible Surface Nets / Transvoxel extraction path.
pub(super) fn rocky_cave_void_signed_distance_metres(
    local_point_metres: DVec3,
    outer_surface_radius_metres: f64,
    seed: u32,
) -> f64 {
    let radial = local_point_metres.length();
    if !radial.is_finite() || radial <= f64::EPSILON {
        return f64::INFINITY;
    }

    let depth_metres = outer_surface_radius_metres - radial;

    // Most clipmap/dense field samples are not inside the shallow cave-bearing
    // crust. Prove those points outside the void before paying for any 3D noise.
    if depth_metres < CAVE_MIN_DEPTH_METRES {
        return CAVE_MIN_DEPTH_METRES - depth_metres;
    }
    if depth_metres > CAVE_MAX_DEPTH_METRES {
        return depth_metres - CAVE_MAX_DEPTH_METRES;
    }

    let point = local_f32(local_point_metres);

    // Two independent tunnel systems at different characteristic scales.
    let major_tunnel = tunnel_intersection_sdf(
        point,
        520.0,
        390.0,
        0.23,
        0.21,
        145.0,
        seed ^ 0x4341_5645, // CAVE
        seed ^ 0x5455_4E4C, // TUNL
        Vec3::new(13.7, -5.1, 8.9),
        Vec3::new(-7.4, 19.2, -11.6),
    );
    let branching_tunnel = tunnel_intersection_sdf(
        point,
        240.0,
        310.0,
        0.20,
        0.18,
        90.0,
        seed ^ 0x4252_414E, // BRAN
        seed ^ 0x4348_4D42, // CHMB
        Vec3::new(-21.3, 4.8, 15.2),
        Vec3::new(6.6, -17.9, 2.7),
    );

    // Sparse blob-like chambers connect into the tunnel systems.
    let chamber_noise = value_noise_3d(
        point / 680.0 + Vec3::new(31.7, -14.1, 9.3),
        seed ^ 0x4348_414D, // CHAM
    );
    let chamber = f64::from(chamber_noise + 0.58) * 110.0;

    let raw_void = major_tunnel.min(branching_tunnel).min(chamber);

    // Keep the cave system in the near-surface crust. A slightly negative
    // minimum depth lets tunnels actually perforate the outer surface and form
    // real entrances instead of sealed underground bubbles.
    raw_void
        .max(CAVE_MIN_DEPTH_METRES - depth_metres)
        .max(depth_metres - CAVE_MAX_DEPTH_METRES)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cave_field_is_deterministic_and_depth_bounded() {
        let radius = 6_371_000.0;
        let seed = 0x4541_5254;
        let point = DVec3::new(120.0, radius - 300.0, -85.0);

        let a = rocky_cave_void_signed_distance_metres(point, radius, seed);
        let b = rocky_cave_void_signed_distance_metres(point, radius, seed);
        assert_eq!(a.to_bits(), b.to_bits());

        let far_above = DVec3::new(0.0, radius + 100.0, 0.0);
        assert!(
            rocky_cave_void_signed_distance_metres(far_above, radius, seed) > 0.0,
            "caves must not create detached void shells above the terrain"
        );

        let too_deep = DVec3::new(0.0, radius - 3_000.0, 0.0);
        assert!(
            rocky_cave_void_signed_distance_metres(too_deep, radius, seed) > 0.0,
            "development caves stay in the near-surface crust"
        );
    }
}
