//! Action-target vocabulary and authored default hardware map.

use super::PlayerAction;

pub(crate) const PLAYER_BIND_TARGETS: &[&str] = &[
    "+forward",
    "+back",
    "+moveleft",
    "+moveright",
    "+jump",
    "+duck",
    "+speed",
    "+viewscale",
    "+attack",
    "+attack2",
    "+use",
    "reload",
    "erase_object",
    "toggle_attitude_law",
    "toggle_thrusters",
    "toggle_rcs",
    "toggle_flight_assist",
    "toggle_cruise",
    "+rollleft",
    "+rollright",
    "+pitchup",
    "+pitchdown",
    "+yawleft",
    "+yawright",
    "toggle_landing",
    "toggle_spatial_demand",
    "toggle_camera",
    "toggle_creative_menu",
    "slot1",
    "slot2",
    "slot3",
    "slot4",
    "slot5",
    "slot6",
    "slot7",
    "slot8",
    "slot9",
];

pub(super) fn bind_target_actions(target: &str) -> Option<(&'static str, &'static [PlayerAction])> {
    use PlayerAction as A;
    let normalized = target.trim().to_ascii_lowercase();
    match normalized.as_str() {
        "+forward" => Some(("+forward", &[A::MoveForward])),
        "+back" | "+backward" => Some(("+back", &[A::MoveBackward])),
        "+moveleft" | "+left" => Some(("+moveleft", &[A::MoveLeft])),
        "+moveright" | "+right" => Some(("+moveright", &[A::MoveRight])),
        "+jump" => Some(("+jump", &[A::Jump, A::Ascend, A::TakeOff])),
        "+duck" | "+crouch" => Some(("+duck", &[A::Crouch, A::Descend])),
        "+speed" | "+sprint" => Some(("+speed", &[A::Sprint, A::Boost, A::FastModifier])),
        "+viewscale" => Some(("+viewscale", &[A::ViewScaleModifier])),
        "+attack" => Some(("+attack", &[A::ItemPrimary])),
        "+attack2" => Some(("+attack2", &[A::ItemSecondary])),
        "+use" => Some(("+use", &[A::Interact])),
        "reload" => Some(("reload", &[A::ItemReload])),
        "erase_object" => Some(("erase_object", &[A::EraseObject])),
        "toggle_attitude_law" | "toggle_local_flight" => {
            Some(("toggle_attitude_law", &[A::ToggleAttitudeLaw]))
        }
        "toggle_thrusters" => Some(("toggle_thrusters", &[A::ToggleThrusters])),
        "toggle_rcs" => Some(("toggle_rcs", &[A::ToggleRcs])),
        "toggle_flight_assist" => Some(("toggle_flight_assist", &[A::ToggleFlightAssist])),
        "toggle_cruise" => Some(("toggle_cruise", &[A::ToggleCruise])),
        "+rollleft" => Some(("+rollleft", &[A::RollLeft])),
        "+rollright" => Some(("+rollright", &[A::RollRight])),
        "+pitchup" => Some(("+pitchup", &[A::PitchUp])),
        "+pitchdown" => Some(("+pitchdown", &[A::PitchDown])),
        "+yawleft" => Some(("+yawleft", &[A::YawLeft])),
        "+yawright" => Some(("+yawright", &[A::YawRight])),
        "toggle_landing" => Some(("toggle_landing", &[A::ToggleLanding])),
        "toggle_spatial_demand" => Some(("toggle_spatial_demand", &[A::ToggleSpatialDemand])),
        "toggle_camera" => Some(("toggle_camera", &[A::ToggleCameraMode])),
        "toggle_creative_menu" => Some(("toggle_creative_menu", &[A::ToggleCreativeMenu])),
        "slot1" => Some(("slot1", &[A::Hotbar1])),
        "slot2" => Some(("slot2", &[A::Hotbar2])),
        "slot3" => Some(("slot3", &[A::Hotbar3])),
        "slot4" => Some(("slot4", &[A::Hotbar4])),
        "slot5" => Some(("slot5", &[A::Hotbar5])),
        "slot6" => Some(("slot6", &[A::Hotbar6])),
        "slot7" => Some(("slot7", &[A::Hotbar7])),
        "slot8" => Some(("slot8", &[A::Hotbar8])),
        "slot9" => Some(("slot9", &[A::Hotbar9])),
        _ => None,
    }
}

/// Authored defaults remain data; all binding mutation uses the same API.
pub(super) const DEFAULT_PLAYER_BINDINGS: &[(&str, &str)] = &[
    ("w", "+forward"),
    ("s", "+back"),
    ("a", "+moveleft"),
    ("d", "+moveright"),
    ("space", "+jump"),
    ("lctrl", "+duck"),
    ("rctrl", "+duck"),
    ("lshift", "+speed"),
    ("rshift", "+speed"),
    ("v", "toggle_attitude_law"),
    ("x", "toggle_thrusters"),
    ("z", "toggle_rcs"),
    ("b", "toggle_flight_assist"),
    ("c", "toggle_cruise"),
    ("q", "+rollleft"),
    ("e", "+rollright"),
    ("up", "+pitchup"),
    ("down", "+pitchdown"),
    ("left", "+yawleft"),
    ("right", "+yawright"),
    ("l", "toggle_landing"),
    ("f5", "toggle_camera"),
    ("lalt", "+viewscale"),
    ("ralt", "+viewscale"),
    ("mouse1", "+attack"),
    ("mouse2", "+attack2"),
    ("mouse3", "erase_object"),
    ("r", "reload"),
    ("tab", "toggle_creative_menu"),
    ("f", "+use"),
    ("1", "slot1"),
    ("2", "slot2"),
    ("3", "slot3"),
    ("4", "slot4"),
    ("5", "slot5"),
    ("6", "slot6"),
    ("7", "slot7"),
    ("8", "slot8"),
    ("9", "slot9"),
];
