//! Bindable device vocabulary and hardware button sampling.

use bevy::prelude::*;

// #56 source-style-runtime-keymap-v1
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum PlayerInputButton {
    Key(KeyCode),
    Mouse(MouseButton),
}

pub(crate) const BINDABLE_INPUT_NAMES: &[&str] = &[
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "space",
    "tab",
    "enter",
    "escape",
    "backquote",
    "lshift",
    "rshift",
    "lctrl",
    "rctrl",
    "lalt",
    "ralt",
    "up",
    "down",
    "left",
    "right",
    "f1",
    "f2",
    "f3",
    "f4",
    "f5",
    "f6",
    "f7",
    "f8",
    "f9",
    "f10",
    "f11",
    "f12",
    "mouse1",
    "mouse2",
    "mouse3",
];

impl PlayerInputButton {
    pub(crate) fn parse(raw: &str) -> Option<Self> {
        use PlayerInputButton::{Key, Mouse};
        let value = raw.trim().to_ascii_lowercase();
        Some(match value.as_str() {
            "a" => Key(KeyCode::KeyA),
            "b" => Key(KeyCode::KeyB),
            "c" => Key(KeyCode::KeyC),
            "d" => Key(KeyCode::KeyD),
            "e" => Key(KeyCode::KeyE),
            "f" => Key(KeyCode::KeyF),
            "g" => Key(KeyCode::KeyG),
            "h" => Key(KeyCode::KeyH),
            "i" => Key(KeyCode::KeyI),
            "j" => Key(KeyCode::KeyJ),
            "k" => Key(KeyCode::KeyK),
            "l" => Key(KeyCode::KeyL),
            "m" => Key(KeyCode::KeyM),
            "n" => Key(KeyCode::KeyN),
            "o" => Key(KeyCode::KeyO),
            "p" => Key(KeyCode::KeyP),
            "q" => Key(KeyCode::KeyQ),
            "r" => Key(KeyCode::KeyR),
            "s" => Key(KeyCode::KeyS),
            "t" => Key(KeyCode::KeyT),
            "u" => Key(KeyCode::KeyU),
            "v" => Key(KeyCode::KeyV),
            "w" => Key(KeyCode::KeyW),
            "x" => Key(KeyCode::KeyX),
            "y" => Key(KeyCode::KeyY),
            "z" => Key(KeyCode::KeyZ),
            "0" => Key(KeyCode::Digit0),
            "1" => Key(KeyCode::Digit1),
            "2" => Key(KeyCode::Digit2),
            "3" => Key(KeyCode::Digit3),
            "4" => Key(KeyCode::Digit4),
            "5" => Key(KeyCode::Digit5),
            "6" => Key(KeyCode::Digit6),
            "7" => Key(KeyCode::Digit7),
            "8" => Key(KeyCode::Digit8),
            "9" => Key(KeyCode::Digit9),
            "space" => Key(KeyCode::Space),
            "tab" => Key(KeyCode::Tab),
            "enter" | "return" => Key(KeyCode::Enter),
            "escape" | "esc" => Key(KeyCode::Escape),
            "backquote" | "grave" | "`" => Key(KeyCode::Backquote),
            "lshift" | "shift" => Key(KeyCode::ShiftLeft),
            "rshift" => Key(KeyCode::ShiftRight),
            "lctrl" | "ctrl" => Key(KeyCode::ControlLeft),
            "rctrl" => Key(KeyCode::ControlRight),
            "lalt" | "alt" => Key(KeyCode::AltLeft),
            "ralt" => Key(KeyCode::AltRight),
            "up" => Key(KeyCode::ArrowUp),
            "down" => Key(KeyCode::ArrowDown),
            "left" => Key(KeyCode::ArrowLeft),
            "right" => Key(KeyCode::ArrowRight),
            "f1" => Key(KeyCode::F1),
            "f2" => Key(KeyCode::F2),
            "f3" => Key(KeyCode::F3),
            "f4" => Key(KeyCode::F4),
            "f5" => Key(KeyCode::F5),
            "f6" => Key(KeyCode::F6),
            "f7" => Key(KeyCode::F7),
            "f8" => Key(KeyCode::F8),
            "f9" => Key(KeyCode::F9),
            "f10" => Key(KeyCode::F10),
            "f11" => Key(KeyCode::F11),
            "f12" => Key(KeyCode::F12),
            "mouse1" | "mouseleft" => Mouse(MouseButton::Left),
            "mouse2" | "mouseright" => Mouse(MouseButton::Right),
            "mouse3" | "mousemiddle" => Mouse(MouseButton::Middle),
            _ => return None,
        })
    }

    pub(crate) fn canonical_name(self) -> String {
        match self {
            Self::Mouse(MouseButton::Left) => "mouse1".to_string(),
            Self::Mouse(MouseButton::Right) => "mouse2".to_string(),
            Self::Mouse(MouseButton::Middle) => "mouse3".to_string(),
            Self::Mouse(other) => format!("{other:?}").to_ascii_lowercase(),
            Self::Key(key) => match key {
                KeyCode::KeyA => "a".into(),
                KeyCode::KeyB => "b".into(),
                KeyCode::KeyC => "c".into(),
                KeyCode::KeyD => "d".into(),
                KeyCode::KeyE => "e".into(),
                KeyCode::KeyF => "f".into(),
                KeyCode::KeyG => "g".into(),
                KeyCode::KeyH => "h".into(),
                KeyCode::KeyI => "i".into(),
                KeyCode::KeyJ => "j".into(),
                KeyCode::KeyK => "k".into(),
                KeyCode::KeyL => "l".into(),
                KeyCode::KeyM => "m".into(),
                KeyCode::KeyN => "n".into(),
                KeyCode::KeyO => "o".into(),
                KeyCode::KeyP => "p".into(),
                KeyCode::KeyQ => "q".into(),
                KeyCode::KeyR => "r".into(),
                KeyCode::KeyS => "s".into(),
                KeyCode::KeyT => "t".into(),
                KeyCode::KeyU => "u".into(),
                KeyCode::KeyV => "v".into(),
                KeyCode::KeyW => "w".into(),
                KeyCode::KeyX => "x".into(),
                KeyCode::KeyY => "y".into(),
                KeyCode::KeyZ => "z".into(),
                KeyCode::Digit0 => "0".into(),
                KeyCode::Digit1 => "1".into(),
                KeyCode::Digit2 => "2".into(),
                KeyCode::Digit3 => "3".into(),
                KeyCode::Digit4 => "4".into(),
                KeyCode::Digit5 => "5".into(),
                KeyCode::Digit6 => "6".into(),
                KeyCode::Digit7 => "7".into(),
                KeyCode::Digit8 => "8".into(),
                KeyCode::Digit9 => "9".into(),
                KeyCode::Space => "space".into(),
                KeyCode::Tab => "tab".into(),
                KeyCode::Enter => "enter".into(),
                KeyCode::Escape => "escape".into(),
                KeyCode::Backquote => "backquote".into(),
                KeyCode::ShiftLeft => "lshift".into(),
                KeyCode::ShiftRight => "rshift".into(),
                KeyCode::ControlLeft => "lctrl".into(),
                KeyCode::ControlRight => "rctrl".into(),
                KeyCode::AltLeft => "lalt".into(),
                KeyCode::AltRight => "ralt".into(),
                KeyCode::ArrowUp => "up".into(),
                KeyCode::ArrowDown => "down".into(),
                KeyCode::ArrowLeft => "left".into(),
                KeyCode::ArrowRight => "right".into(),
                KeyCode::F1 => "f1".into(),
                KeyCode::F2 => "f2".into(),
                KeyCode::F3 => "f3".into(),
                KeyCode::F4 => "f4".into(),
                KeyCode::F5 => "f5".into(),
                KeyCode::F6 => "f6".into(),
                KeyCode::F7 => "f7".into(),
                KeyCode::F8 => "f8".into(),
                KeyCode::F9 => "f9".into(),
                KeyCode::F10 => "f10".into(),
                KeyCode::F11 => "f11".into(),
                KeyCode::F12 => "f12".into(),
                other => format!("{other:?}").to_ascii_lowercase(),
            },
        }
    }

    pub(super) fn pressed(
        self,
        keyboard: &ButtonInput<KeyCode>,
        mouse: &ButtonInput<MouseButton>,
    ) -> bool {
        match self {
            Self::Key(key) => keyboard.pressed(key),
            Self::Mouse(button) => mouse.pressed(button),
        }
    }

    pub(super) fn just_pressed(
        self,
        keyboard: &ButtonInput<KeyCode>,
        mouse: &ButtonInput<MouseButton>,
    ) -> bool {
        match self {
            Self::Key(key) => keyboard.just_pressed(key),
            Self::Mouse(button) => mouse.just_pressed(button),
        }
    }

    pub(super) fn just_released(
        self,
        keyboard: &ButtonInput<KeyCode>,
        mouse: &ButtonInput<MouseButton>,
    ) -> bool {
        match self {
            Self::Key(key) => keyboard.just_released(key),
            Self::Mouse(button) => mouse.just_released(button),
        }
    }
}

pub(super) fn key_label(key: KeyCode) -> String {
    match key {
        KeyCode::KeyW => "W".into(),
        KeyCode::KeyA => "A".into(),
        KeyCode::KeyS => "S".into(),
        KeyCode::KeyD => "D".into(),
        KeyCode::KeyC => "C".into(),
        KeyCode::KeyE => "E".into(),
        KeyCode::KeyL => "L".into(),
        KeyCode::KeyR => "R".into(),
        KeyCode::KeyV => "V".into(),
        KeyCode::KeyX => "X".into(),
        KeyCode::KeyZ => "Z".into(),
        KeyCode::Space => "SPACE".into(),
        KeyCode::ControlLeft | KeyCode::ControlRight => "CTRL".into(),
        KeyCode::ShiftLeft | KeyCode::ShiftRight => "SHIFT".into(),
        KeyCode::AltLeft | KeyCode::AltRight => "ALT".into(),
        KeyCode::Tab => "TAB".into(),
        KeyCode::F5 => "F5".into(),
        KeyCode::Digit1 => "1".into(),
        KeyCode::Digit2 => "2".into(),
        KeyCode::Digit3 => "3".into(),
        KeyCode::Digit4 => "4".into(),
        KeyCode::Digit5 => "5".into(),
        KeyCode::Digit6 => "6".into(),
        KeyCode::Digit7 => "7".into(),
        KeyCode::Digit8 => "8".into(),
        KeyCode::Digit9 => "9".into(),
        other => format!("{other:?}"),
    }
}
