[camera]
default_zoom = 3.5
min_zoom = 0.03125
max_zoom = 32.0
base_zoom_speed = 5.0
follow_smoothness = 0.15

[chunk]
size = 64.0
default_z = -10.0
texture_generator_shader = "texture_generators/example_uv"

[chunk_loader]
default_radius = 8

[debug]
spawn_debug_objects = false

[entity]
reservation_buffer_size = 8

[log.tracing]
enabled = true

[player]
size = 32.0
movement_speed = 150.0
sprint_multiplier = 2.5

[time]
start_paused = false
start_step_secs = 0.02

[utils.premium_box]
success_logging_enabled = false

[workflow]
timeout_frames_per_stage = 30
max_retries = 5
runner_logging_blacklist = "Chunk::*, ChunkLoader::*"