use std::{
    any::{Any, TypeId},
    collections::HashMap,
};

use bevy::prelude::*;

use super::{FocusTarget, StructureItemId};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectSectionId(pub &'static str);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectFieldId(pub &'static str);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectActionId(pub &'static str);

/// Stable optional override for value-widget selection.
///
/// The ID lives in UI-agnostic metadata. An egui host, terminal host, or other
/// presentation layer may resolve the same semantic hint differently.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectWidgetId(pub &'static str);

/// How an inspected value may be changed.
///
/// This is intentionally richer than a `read_only: bool`: presentation consumes
/// authority supplied by the domain; it never creates authority merely because
/// `&mut T` happens to be technically obtainable.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InspectAccess {
    #[default]
    ReadOnly,
    /// The inspected value itself is authoritative and may be mutated directly.
    Direct,
    /// Changes must pass through validation/setter logic.
    Validated,
    /// Changes belong to an authoring transaction/undo history.
    Transactional,
    /// Changes are requests/commands to the owning domain rather than field writes.
    Command,
}

impl InspectAccess {
    pub fn editable(self) -> bool {
        self != Self::ReadOnly
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::ReadOnly => "read-only",
            Self::Direct => "direct",
            Self::Validated => "validated",
            Self::Transactional => "transactional",
            Self::Command => "command",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InspectUnit(pub &'static str);

impl InspectUnit {
    pub const KELVIN: Self = Self("K");
    pub const JOULE: Self = Self("J");
    pub const WATT: Self = Self("W");
    pub const HEAT_CAPACITY: Self = Self("J/K");
    pub const COOLING_COEFFICIENT: Self = Self("W/K");
    pub const METER: Self = Self("m");
    pub const METERS_PER_SECOND: Self = Self("m/s");
    pub const METERS_PER_SECOND_SQUARED: Self = Self("m/s²");
    pub const DENSITY: Self = Self("kg/m³");
    pub const SPECIFIC_HEAT_CAPACITY: Self = Self("J/(kg·K)");
    pub const THERMAL_CONDUCTIVITY: Self = Self("W/(m·K)");
    pub const THERMAL_DIFFUSIVITY: Self = Self("m²/s");
}

#[derive(Debug, Clone, Copy)]
pub struct InspectNumberFormat {
    pub significant_digits: u8,
}

impl Default for InspectNumberFormat {
    fn default() -> Self {
        Self {
            significant_digits: 5,
        }
    }
}

impl InspectNumberFormat {
    pub const fn significant_digits(significant_digits: u8) -> Self {
        Self { significant_digits }
    }
}

/// UI hints for numeric input. These are presentation affordances, not domain
/// validation. Domains must still validate every edit request they accept.
#[derive(Debug, Clone, Copy)]
pub struct InspectNumberInput {
    pub speed: f64,
    pub minimum: Option<f64>,
    pub maximum: Option<f64>,
    pub slider: bool,
}

impl Default for InspectNumberInput {
    fn default() -> Self {
        Self {
            speed: 0.1,
            minimum: None,
            maximum: None,
            slider: false,
        }
    }
}

impl InspectNumberInput {
    pub const fn speed(speed: f64) -> Self {
        Self {
            speed,
            minimum: None,
            maximum: None,
            slider: false,
        }
    }

    pub const fn range(mut self, minimum: f64, maximum: f64) -> Self {
        self.minimum = Some(minimum);
        self.maximum = Some(maximum);
        self
    }

    pub const fn slider(mut self) -> Self {
        self.slider = true;
        self
    }
}

/// Static metadata generated by [`Inspect`] implementations.
///
/// This contains presentation-independent meaning only. In particular, a widget
/// override is a stable ID rather than an egui callback/function pointer.
#[derive(Debug, Clone, Copy)]
pub struct InspectFieldMetadata {
    pub id: InspectFieldId,
    pub rust_name: &'static str,
    pub rust_type_name: &'static str,
    pub label: &'static str,
    pub symbol: Option<&'static str>,
    pub access: InspectAccess,
    pub unit: Option<InspectUnit>,
    pub hint: Option<&'static str>,
    pub role: Option<&'static str>,
    pub widget: Option<InspectWidgetId>,
    pub number_input: Option<InspectNumberInput>,
}

impl InspectFieldMetadata {
    pub const fn new(
        id: InspectFieldId,
        rust_name: &'static str,
        rust_type_name: &'static str,
        label: &'static str,
    ) -> Self {
        Self {
            id,
            rust_name,
            rust_type_name,
            label,
            symbol: None,
            access: InspectAccess::ReadOnly,
            unit: None,
            hint: None,
            role: None,
            widget: None,
            number_input: None,
        }
    }
}

#[derive(Debug)]
pub struct InspectTypeMetadata {
    pub rust_name: &'static str,
    pub label: &'static str,
    pub fields: &'static [InspectFieldMetadata],
}

/// UI-agnostic field traversal for inspectable values.
///
/// The derive emits this traversal. Presentation hosts choose how to render the
/// values and whether they possess a legal edit capability.
pub trait InspectFieldVisitor {
    fn field(&mut self, metadata: &'static InspectFieldMetadata, value: &dyn Any);
}

/// Mutable traversal deliberately exposes `&mut` only for fields whose metadata
/// declares [`InspectAccess::Direct`]. Validated/transactional/command fields are
/// visited through `read_only` and require an explicit adapter/request path.
pub trait InspectFieldVisitorMut {
    fn read_only(&mut self, metadata: &'static InspectFieldMetadata, value: &dyn Any);
    fn direct(&mut self, metadata: &'static InspectFieldMetadata, value: &mut dyn Any);
}

/// Type-level opt-in for reusable structured inspection.
///
/// `#[derive(Inspect)]` implements this trait for ordinary named-field structs.
/// Manual implementations remain a first-class path for computed properties,
/// setters, polymorphism, collections, or any type whose semantics are richer
/// than stored fields.
pub trait Inspect: Any {
    fn inspect_type_metadata() -> &'static InspectTypeMetadata
    where
        Self: Sized;

    fn visit_inspect_fields(&self, visitor: &mut dyn InspectFieldVisitor);
    fn visit_inspect_fields_mut(&mut self, visitor: &mut dyn InspectFieldVisitorMut);
}

#[derive(Clone, Copy)]
pub struct InspectTypeRegistration {
    type_id: TypeId,
    metadata: &'static InspectTypeMetadata,
    visit: fn(&dyn Any, &mut dyn InspectFieldVisitor) -> bool,
    visit_mut: fn(&mut dyn Any, &mut dyn InspectFieldVisitorMut) -> bool,
}

impl InspectTypeRegistration {
    fn of<T: Inspect>() -> Self {
        Self {
            type_id: TypeId::of::<T>(),
            metadata: T::inspect_type_metadata(),
            visit: visit_erased::<T>,
            visit_mut: visit_erased_mut::<T>,
        }
    }

    pub fn type_id(self) -> TypeId {
        self.type_id
    }

    pub fn metadata(self) -> &'static InspectTypeMetadata {
        self.metadata
    }

    pub fn visit(self, value: &dyn Any, visitor: &mut dyn InspectFieldVisitor) -> bool {
        (self.visit)(value, visitor)
    }

    pub fn visit_mut(
        self,
        value: &mut dyn Any,
        visitor: &mut dyn InspectFieldVisitorMut,
    ) -> bool {
        (self.visit_mut)(value, visitor)
    }
}

fn visit_erased<T: Inspect>(value: &dyn Any, visitor: &mut dyn InspectFieldVisitor) -> bool {
    let Some(value) = value.downcast_ref::<T>() else {
        return false;
    };
    value.visit_inspect_fields(visitor);
    true
}

fn visit_erased_mut<T: Inspect>(
    value: &mut dyn Any,
    visitor: &mut dyn InspectFieldVisitorMut,
) -> bool {
    let Some(value) = value.downcast_mut::<T>() else {
        return false;
    };
    value.visit_inspect_fields_mut(visitor);
    true
}

/// Runtime catalog for externally registered inspectable Rust types.
///
/// Registration is explicit: deriving [`Inspect`] describes a type, while an app
/// registers only the types it wants discoverable through type erasure.
#[derive(Resource, Default)]
pub struct InspectTypeRegistry {
    registrations: HashMap<TypeId, InspectTypeRegistration>,
}

impl InspectTypeRegistry {
    pub fn register<T: Inspect>(&mut self) {
        self.registrations
            .entry(TypeId::of::<T>())
            .or_insert_with(InspectTypeRegistration::of::<T>);
    }

    pub fn get<T: Inspect>(&self) -> Option<InspectTypeRegistration> {
        self.get_by_type_id(TypeId::of::<T>())
    }

    pub fn get_by_type_id(&self, type_id: TypeId) -> Option<InspectTypeRegistration> {
        self.registrations.get(&type_id).copied()
    }

    pub fn registrations(&self) -> impl Iterator<Item = InspectTypeRegistration> + '_ {
        self.registrations.values().copied()
    }
}

pub trait AppInspectExt {
    fn register_inspectable<T: Inspect>(&mut self) -> &mut Self;
}

impl AppInspectExt for App {
    fn register_inspectable<T: Inspect>(&mut self) -> &mut Self {
        self.init_resource::<InspectTypeRegistry>();
        self.world_mut()
            .resource_mut::<InspectTypeRegistry>()
            .register::<T>();
        self
    }
}

#[derive(Debug, Clone)]
pub enum InspectValue {
    Text(String),
    Bool(bool),
    Integer(i64),
    Number {
        value: f64,
        format: InspectNumberFormat,
    },
    Quantity {
        value: f64,
        unit: InspectUnit,
        format: InspectNumberFormat,
    },
    Range {
        minimum: f64,
        maximum: f64,
        unit: InspectUnit,
        format: InspectNumberFormat,
    },
    Entity(Entity),
    Vec3(Vec3),
}

impl InspectValue {
    pub fn text(value: impl Into<String>) -> Self {
        Self::Text(value.into())
    }

    pub fn number(value: impl Into<f64>) -> Self {
        Self::Number {
            value: value.into(),
            format: InspectNumberFormat::default(),
        }
    }

    pub fn quantity(value: impl Into<f64>, unit: InspectUnit) -> Self {
        Self::Quantity {
            value: value.into(),
            unit,
            format: InspectNumberFormat::default(),
        }
    }

    pub fn quantity_with_format(
        value: impl Into<f64>,
        unit: InspectUnit,
        format: InspectNumberFormat,
    ) -> Self {
        Self::Quantity {
            value: value.into(),
            unit,
            format,
        }
    }

    pub fn as_number(&self) -> Option<f64> {
        match self {
            Self::Number { value, .. } | Self::Quantity { value, .. } => Some(*value),
            _ => None,
        }
    }
}

#[derive(Debug, Clone)]
pub struct InspectField {
    pub id: Option<InspectFieldId>,
    pub label: String,
    pub symbol: Option<&'static str>,
    pub value: InspectValue,
    pub access: InspectAccess,
    pub hint: Option<String>,
    pub number_input: Option<InspectNumberInput>,
}

impl InspectField {
    pub fn new(label: impl Into<String>, value: InspectValue) -> Self {
        Self {
            id: None,
            label: label.into(),
            symbol: None,
            value,
            access: InspectAccess::ReadOnly,
            hint: None,
            number_input: None,
        }
    }

    pub fn symbol(mut self, symbol: &'static str) -> Self {
        self.symbol = Some(symbol);
        self
    }

    pub fn access(mut self, access: InspectAccess) -> Self {
        self.access = access;
        self
    }

    pub fn editable(mut self, id: InspectFieldId, access: InspectAccess) -> Self {
        debug_assert!(access.editable());
        self.id = Some(id);
        self.access = access;
        self
    }

    pub fn hint(mut self, hint: impl Into<String>) -> Self {
        self.hint = Some(hint.into());
        self
    }

    pub fn number_input(mut self, input: InspectNumberInput) -> Self {
        self.number_input = Some(input);
        self
    }
}

#[derive(Debug, Clone)]
pub struct InspectAction {
    pub id: InspectActionId,
    pub label: String,
    pub hint: Option<String>,
}

impl InspectAction {
    pub fn new(id: InspectActionId, label: impl Into<String>) -> Self {
        Self {
            id,
            label: label.into(),
            hint: None,
        }
    }

    pub fn hint(mut self, hint: impl Into<String>) -> Self {
        self.hint = Some(hint.into());
        self
    }
}

#[derive(Debug, Clone)]
pub struct InspectSection {
    pub id: InspectSectionId,
    pub title: String,
    pub order: i32,
    pub structure_item: Option<StructureItemId>,
    pub contextual_gizmo: bool,
    pub fields: Vec<InspectField>,
    pub actions: Vec<InspectAction>,
}

impl InspectSection {
    pub fn new(id: InspectSectionId, title: impl Into<String>, order: i32) -> Self {
        Self {
            id,
            title: title.into(),
            order,
            structure_item: None,
            contextual_gizmo: false,
            fields: Vec::new(),
            actions: Vec::new(),
        }
    }

    pub fn for_structure(mut self, structure_item: StructureItemId) -> Self {
        self.structure_item = Some(structure_item);
        self
    }

    pub fn contextual_gizmo(mut self) -> Self {
        self.contextual_gizmo = true;
        self
    }

    pub fn field(mut self, field: InspectField) -> Self {
        self.fields.push(field);
        self
    }

    pub fn action(mut self, action: InspectAction) -> Self {
        self.actions.push(action);
        self
    }
}

/// Proposed semantic field edit emitted by an inspection UI host.
///
/// This is a request, never authority. The owning domain must re-check target,
/// access, invariants and persistence semantics before applying it.
#[derive(Message, Debug, Clone)]
pub struct InspectEditRequest {
    pub target: FocusTarget,
    pub section: InspectSectionId,
    pub field: InspectFieldId,
    pub value: InspectValue,
}

/// Contextual operation emitted by an inspection/gizmo UI host.
#[derive(Message, Debug, Clone, Copy)]
pub struct InspectActionRequest {
    pub target: FocusTarget,
    pub section: InspectSectionId,
    pub action: InspectActionId,
}

/// One frame of structured semantic inspection data for the canonical focus.
#[derive(Resource, Debug, Default)]
pub struct InspectionFrame {
    sections: Vec<InspectSection>,
}

impl InspectionFrame {
    pub fn submit(&mut self, section: InspectSection) {
        assert!(
            !self.sections.iter().any(|existing| existing.id == section.id),
            "duplicate inspection section id {}",
            section.id.0,
        );
        self.sections.push(section);
    }

    pub fn sections(&self) -> &[InspectSection] {
        &self.sections
    }

    pub fn section(&self, id: InspectSectionId) -> Option<&InspectSection> {
        self.sections.iter().find(|section| section.id == id)
    }

    pub fn sorted_sections(&self) -> Vec<&InspectSection> {
        self.sorted_sections_for(None)
    }

    /// `None` means whole-entity inspection and therefore returns all sections.
    pub fn sorted_sections_for(&self, structure_item: Option<StructureItemId>) -> Vec<&InspectSection> {
        let mut sections = self
            .sections
            .iter()
            .filter(|section| {
                structure_item.is_none() || section.structure_item == structure_item
            })
            .collect::<Vec<_>>();
        sections.sort_by(|a, b| {
            a.order
                .cmp(&b.order)
                .then_with(|| a.title.cmp(&b.title))
        });
        sections
    }

    fn clear(&mut self) {
        self.sections.clear();
    }
}

pub(super) fn clear_inspection_frame(mut frame: ResMut<InspectionFrame>) {
    frame.clear();
}

#[cfg(test)]
mod inspect_derive_tests {
    use std::any::Any;

    use super::*;

    #[derive(crate::Inspect)]
    #[inspect(label = "Derived example")]
    struct DerivedExample {
        #[inspect(
            direct,
            label = "Opacity",
            role = "opacity",
            widget = "tests.opacity",
            speed = 0.01,
            range = 0.0..=1.0,
            slider
        )]
        opacity: f32,
        #[inspect(validated, unit = "K", hint = "Validation belongs to the domain adapter.")]
        temperature_kelvin: f32,
        #[inspect(skip)]
        cache: u32,
    }

    struct MutabilityProbe {
        direct: usize,
        read_only: usize,
    }

    impl InspectFieldVisitorMut for MutabilityProbe {
        fn read_only(&mut self, _: &'static InspectFieldMetadata, _: &dyn Any) {
            self.read_only += 1;
        }

        fn direct(&mut self, _: &'static InspectFieldMetadata, value: &mut dyn Any) {
            self.direct += 1;
            *value
                .downcast_mut::<f32>()
                .expect("the direct test field is f32") = 0.75;
        }
    }

    #[test]
    fn derive_describes_fields_without_leaking_non_direct_mutability() {
        let metadata = DerivedExample::inspect_type_metadata();
        assert_eq!(metadata.label, "Derived example");
        assert_eq!(metadata.fields.len(), 2);

        let opacity = metadata.fields[0];
        assert_eq!(opacity.id, InspectFieldId("opacity"));
        assert_eq!(opacity.label, "Opacity");
        assert_eq!(opacity.role, Some("opacity"));
        assert_eq!(opacity.widget, Some(InspectWidgetId("tests.opacity")));
        assert_eq!(opacity.access, InspectAccess::Direct);
        assert!(opacity.number_input.expect("numeric metadata").slider);

        let temperature = metadata.fields[1];
        assert_eq!(temperature.access, InspectAccess::Validated);
        assert_eq!(temperature.unit, Some(InspectUnit::KELVIN));

        let mut value = DerivedExample {
            opacity: 0.25,
            temperature_kelvin: 350.0,
            cache: 7,
        };
        let mut probe = MutabilityProbe {
            direct: 0,
            read_only: 0,
        };
        value.visit_inspect_fields_mut(&mut probe);

        assert_eq!(probe.direct, 1);
        assert_eq!(probe.read_only, 1);
        assert_eq!(value.opacity, 0.75);
        assert_eq!(value.temperature_kelvin, 350.0);
        assert_eq!(value.cache, 7);
    }
}
