#pragma kernel CSMain

struct FilamentGenerationSettings
{
    int ChunkSize;
    float MapFromMin;
    float MapFromMax;
    float MapToMin;
    float MapToMax;
    float UniverseNoiseInfluence;
    float Power;
    float Amplitude;
};

FilamentGenerationSettings filamentGenerationSettings;

RWStructuredBuffer<float> universeDensityMap;

RWStructuredBuffer<float> electronDensityMap;
RWStructuredBuffer<float> positronDensityMap;
RWStructuredBuffer<float> protonDensityMap;
RWStructuredBuffer<float> antiProtonDensityMap;
RWStructuredBuffer<float> neutronDensityMap;
RWStructuredBuffer<float> antiNeutronDensityMap;

float Map(float value, float fromMin, float fromMax, float toMin, float toMax)
{
    return (value - fromMin) / (fromMax - fromMin) * (toMax - toMin) + toMin;
}

float ProcessElectronDensity(float electronDensity, float universeDensity)
{
    electronDensity = Map(electronDensity, filamentGenerationSettings.MapFromMin, filamentGenerationSettings.MapFromMax, filamentGenerationSettings.MapToMin, filamentGenerationSettings.MapToMax);
    electronDensity = pow(electronDensity, filamentGenerationSettings.Power);
    electronDensity = electronDensity * filamentGenerationSettings.Amplitude;
    
    // TODO: Implement actual algorithm
    electronDensity = electronDensity * (1 + (filamentGenerationSettings.UniverseNoiseInfluence * universeDensity));
    return electronDensity;
}

float ProcessPositronDensity(float positronDensity, float universeDensity)
{
    positronDensity = Map(positronDensity, filamentGenerationSettings.MapFromMin, filamentGenerationSettings.MapFromMax, filamentGenerationSettings.MapToMin, filamentGenerationSettings.MapToMax);
    positronDensity = pow(positronDensity, filamentGenerationSettings.Power);
    positronDensity = positronDensity * filamentGenerationSettings.Amplitude;
    
    // TODO: Implement actual algorithm
    positronDensity = positronDensity * (1 + (filamentGenerationSettings.UniverseNoiseInfluence * universeDensity));
    return positronDensity;
}

float ProcessProtonDensity(float protonDensity, float universeDensity)
{
    protonDensity = Map(protonDensity, filamentGenerationSettings.MapFromMin, filamentGenerationSettings.MapFromMax, filamentGenerationSettings.MapToMin, filamentGenerationSettings.MapToMax);
    protonDensity = pow(protonDensity, filamentGenerationSettings.Power);
    protonDensity = protonDensity * filamentGenerationSettings.Amplitude;
    
    // TODO: Implement actual algorithm
    protonDensity = protonDensity * (1 + (filamentGenerationSettings.UniverseNoiseInfluence * universeDensity));
    return protonDensity;
}

float ProcessAntiProtonDensity(float antiProtonDensity, float universeDensity)
{
    antiProtonDensity = Map(antiProtonDensity, filamentGenerationSettings.MapFromMin, filamentGenerationSettings.MapFromMax, filamentGenerationSettings.MapToMin, filamentGenerationSettings.MapToMax);
    antiProtonDensity = pow(antiProtonDensity, filamentGenerationSettings.Power);
    antiProtonDensity = antiProtonDensity * filamentGenerationSettings.Amplitude;
    
    // TODO: Implement actual algorithm
    antiProtonDensity = antiProtonDensity * (1 + (filamentGenerationSettings.UniverseNoiseInfluence * universeDensity));
    return antiProtonDensity;
}

float ProcessNeutronDensity(float neutronDensity, float universeDensity)
{
    neutronDensity = Map(neutronDensity, filamentGenerationSettings.MapFromMin, filamentGenerationSettings.MapFromMax, filamentGenerationSettings.MapToMin, filamentGenerationSettings.MapToMax);
    neutronDensity = pow(neutronDensity, filamentGenerationSettings.Power);
    neutronDensity = neutronDensity * filamentGenerationSettings.Amplitude;
    
    // TODO: Implement actual algorithm
    neutronDensity = neutronDensity * (1 + (filamentGenerationSettings.UniverseNoiseInfluence * universeDensity));
    return neutronDensity;
}

float ProcessAntiNeutronDensity(float antiNeutronDensity, float universeDensity)
{
    antiNeutronDensity = Map(antiNeutronDensity, filamentGenerationSettings.MapFromMin, filamentGenerationSettings.MapFromMax, filamentGenerationSettings.MapToMin, filamentGenerationSettings.MapToMax);
    antiNeutronDensity = pow(antiNeutronDensity, filamentGenerationSettings.Power);
    antiNeutronDensity = antiNeutronDensity * filamentGenerationSettings.Amplitude;
    
    // TODO: Implement actual algorithm
    antiNeutronDensity = antiNeutronDensity * (1 + (filamentGenerationSettings.UniverseNoiseInfluence * universeDensity));
    return antiNeutronDensity;
}

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int x = id.x;
    int y = id.y;
    int index = y * filamentGenerationSettings.ChunkSize + x;
    electronDensityMap[index] = ProcessElectronDensity(electronDensityMap[index], universeDensityMap[index]);
    positronDensityMap[index] = ProcessPositronDensity(positronDensityMap[index], universeDensityMap[index]);
    protonDensityMap[index] = ProcessProtonDensity(protonDensityMap[index], universeDensityMap[index]);
    antiProtonDensityMap[index] = ProcessAntiProtonDensity(antiProtonDensityMap[index], universeDensityMap[index]);
    neutronDensityMap[index] = ProcessNeutronDensity(neutronDensityMap[index], universeDensityMap[index]);
    antiNeutronDensityMap[index] = ProcessAntiNeutronDensity(antiNeutronDensityMap[index], universeDensityMap[index]);
}
