#pragma kernel CSMain

struct SectorGenerationSettings
{
    int ChunkSize;
    float MapFromMin;
    float MapFromMax;
    float MapToMin;
    float MapToMax;
    float FilamentNoiseInfluence;
    float Power;
    float Amplitude;
};

RWStructuredBuffer<SectorGenerationSettings> sectorGenerationSettingsBuffer;
RWStructuredBuffer<float> electronDensityMap;
RWStructuredBuffer<float> positronDensityMap;
RWStructuredBuffer<float> protonDensityMap;
RWStructuredBuffer<float> antiProtonDensityMap;
RWStructuredBuffer<float> neutronDensityMap;
RWStructuredBuffer<float> antiNeutronDensityMap;
RWStructuredBuffer<float> solidParticleDensityMap;
RWStructuredBuffer<float> liquidParticleDensityMap;
RWStructuredBuffer<float> gasParticleDensityMap;
RWStructuredBuffer<float> plasmaParticleDensityMap;

float Map(float value, float fromMin, float fromMax, float toMin, float toMax)
{
    return (value - fromMin) / (fromMax - fromMin) * (toMax - toMin) + toMin;
}

float ProcessSolidParticleDensity(float solidParticleDensity, float electronDensity, float positronDensity, float protonDensity, float antiProtonDensity, float neutronDensity, float antiNeutronDensity)
{
    solidParticleDensity = Map(solidParticleDensity, sectorGenerationSettingsBuffer[0].MapFromMin, sectorGenerationSettingsBuffer[0].MapFromMax, sectorGenerationSettingsBuffer[0].MapToMin, sectorGenerationSettingsBuffer[0].MapToMax);
    solidParticleDensity = pow(solidParticleDensity, sectorGenerationSettingsBuffer[0].Power);
    solidParticleDensity = solidParticleDensity * sectorGenerationSettingsBuffer[0].Amplitude;
    
    // TODO: Implement actual algorithm
    solidParticleDensity = solidParticleDensity * (1 + (sectorGenerationSettingsBuffer[0].FilamentNoiseInfluence * electronDensity));
    return solidParticleDensity;
}

float ProcessLiquidParticleDensity(float liquidParticleDensity, float electronDensity, float positronDensity, float protonDensity, float antiProtonDensity, float neutronDensity, float antiNeutronDensity)
{
    liquidParticleDensity = Map(liquidParticleDensity, sectorGenerationSettingsBuffer[0].MapFromMin, sectorGenerationSettingsBuffer[0].MapFromMax, sectorGenerationSettingsBuffer[0].MapToMin, sectorGenerationSettingsBuffer[0].MapToMax);
    liquidParticleDensity = pow(liquidParticleDensity, sectorGenerationSettingsBuffer[0].Power);
    liquidParticleDensity = liquidParticleDensity * sectorGenerationSettingsBuffer[0].Amplitude;
    
    // TODO: Implement actual algorithm
    liquidParticleDensity = liquidParticleDensity * (1 + (sectorGenerationSettingsBuffer[0].FilamentNoiseInfluence * electronDensity));
    return liquidParticleDensity;
}

float ProcessGasParticleDensity(float gasParticleDensity, float electronDensity, float positronDensity, float protonDensity, float antiProtonDensity, float neutronDensity, float antiNeutronDensity)
{
    gasParticleDensity = Map(gasParticleDensity, sectorGenerationSettingsBuffer[0].MapFromMin, sectorGenerationSettingsBuffer[0].MapFromMax, sectorGenerationSettingsBuffer[0].MapToMin, sectorGenerationSettingsBuffer[0].MapToMax);
    gasParticleDensity = pow(gasParticleDensity, sectorGenerationSettingsBuffer[0].Power);
    gasParticleDensity = gasParticleDensity * sectorGenerationSettingsBuffer[0].Amplitude;
    
    // TODO: Implement actual algorithm
    gasParticleDensity = gasParticleDensity * (1 + (sectorGenerationSettingsBuffer[0].FilamentNoiseInfluence * electronDensity));
    return gasParticleDensity;
}

float ProcessPlasmaParticleDensity(float plasmaParticleDensity, float electronDensity, float positronDensity, float protonDensity, float antiProtonDensity, float neutronDensity, float antiNeutronDensity)
{
    plasmaParticleDensity = Map(plasmaParticleDensity, sectorGenerationSettingsBuffer[0].MapFromMin, sectorGenerationSettingsBuffer[0].MapFromMax, sectorGenerationSettingsBuffer[0].MapToMin, sectorGenerationSettingsBuffer[0].MapToMax);
    plasmaParticleDensity = pow(plasmaParticleDensity, sectorGenerationSettingsBuffer[0].Power);
    plasmaParticleDensity = plasmaParticleDensity * sectorGenerationSettingsBuffer[0].Amplitude;
    
    // TODO: Implement actual algorithm
    plasmaParticleDensity = plasmaParticleDensity * (1 + (sectorGenerationSettingsBuffer[0].FilamentNoiseInfluence * electronDensity));
    return plasmaParticleDensity;
}

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int x = id.x;
    int y = id.y;
    int index = y * sectorGenerationSettingsBuffer[0].ChunkSize + x;
    solidParticleDensityMap[index] = ProcessSolidParticleDensity(solidParticleDensityMap[index], electronDensityMap[index], positronDensityMap[index], protonDensityMap[index], antiProtonDensityMap[index], neutronDensityMap[index], antiNeutronDensityMap[index]);
    liquidParticleDensityMap[index] = ProcessLiquidParticleDensity(liquidParticleDensityMap[index], electronDensityMap[index], positronDensityMap[index], protonDensityMap[index], antiProtonDensityMap[index], neutronDensityMap[index], antiNeutronDensityMap[index]);
    gasParticleDensityMap[index] = ProcessGasParticleDensity(gasParticleDensityMap[index], electronDensityMap[index], positronDensityMap[index], protonDensityMap[index], antiProtonDensityMap[index], neutronDensityMap[index], antiNeutronDensityMap[index]);
    plasmaParticleDensityMap[index] = ProcessPlasmaParticleDensity(plasmaParticleDensityMap[index], electronDensityMap[index], positronDensityMap[index], protonDensityMap[index], antiProtonDensityMap[index], neutronDensityMap[index], antiNeutronDensityMap[index]);
}
