[camera]
default_zoom = 1
min_zoom = 0.03125
max_zoom = 32.0
base_zoom_speed = 5.0
follow_smoothness = 0.15

[chunk]
size = 1024
default_z = -10.0
texture_generator_shader = "texture_generators/example_dev"

[chunk_loader]
default_radius = 4
current_view_scale = 0
zoom_cooldown_secs = 1.0

[debug]
spawn_debug_objects = false

[entity]
reservation_buffer_size = 8

[gpu.texture_generator]
workgroup_size_x = 16
workgroup_size_y = 16

[log.tracing]
enabled = true

[player]
base_size = 32.0
base_movement_speed = 32.0
sprint_multiplier = 2.5

[time]
start_paused = false
start_step_secs = 0.02

[utils.premium_box]
success_logging_enabled = false

[workflow]
timeout_frames_per_stage = 30
max_retries = 5
runner_logging_blacklist = "Chunk::*, ChunkLoader::*"