[package]
name = "spacetime_engine_macro"
version = "0.1.0"
edition = "2021"

[lib]
name = "spacetime_engine_macro"
path = "src/lib.rs"
proc-macro = true

[dependencies]
spacetime_engine_macro_lib = { path = "../spacetime_engine_macro_lib" }
syn = "2.0"
proc-macro2 = "1.0"
quote = "1.0"