[package]
name = "loo_cast_base_mod"
version = "0.5.0"
edition = "2021"

[lib]
name = "loo_cast_base_mod"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bevy = "0.11.2"
spacetime_engine = { path = "../spacetime_engine" }